#!/usr/bin/env python3
"""Documentation index generator and membership checker.

Governed by PLATFORM-STANDARDS section 14 and docs/documentation-policy.md.
Deterministic, no AI, no third-party dependencies.

Usage:
  docs_index.py generate [REPO_ROOT]   # write DOCS.md from in-scope markdown
  docs_index.py check [REPO_ROOT]      # advisory membership check (always exit 0)
  docs_index.py check --strict [ROOT]  # membership check, exit 1 on a finding

Scope: every in-scope markdown file must appear in DOCS.md, and every DOCS.md
entry must resolve. Frontmatter (if present) supplies the type, title, and
doc_status used for grouping; files without frontmatter are listed as
unclassified (pending migration phases M1 and M2).
"""
import os
import sys

EXCLUDE_DIRS = {
    ".git", "node_modules", ".next", "generated", "dist",
    "archive", "data", "blog",
}
INDEX_FILE = "DOCS.md"
TYPE_ORDER = [
    "standard", "adr", "decision-log", "reference", "spec",
    "runbook", "worklist", "strategy", "historical", "unclassified",
]


def in_scope(root):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
        for name in filenames:
            if name.endswith(".md"):
                full = os.path.join(dirpath, name)
                rel = os.path.relpath(full, root)
                if rel == INDEX_FILE:
                    continue
                yield rel, full


def read_frontmatter(path):
    """Return (type, title, doc_status). Minimal parse, no yaml dependency."""
    ftype = title = status = None
    try:
        with open(path, "r", encoding="utf-8") as fh:
            lines = fh.read().splitlines()
    except OSError:
        return None, None, None
    if lines and lines[0].strip() == "---":
        for line in lines[1:]:
            if line.strip() == "---":
                break
            if line.startswith("type:"):
                ftype = line.split(":", 1)[1].strip()
            elif line.startswith("title:"):
                title = line.split(":", 1)[1].strip()
            elif line.startswith("doc_status:"):
                status = line.split(":", 1)[1].strip()
    if not title:
        for line in lines:
            if line.startswith("# "):
                title = line[2:].strip()
                break
    return ftype, title, status


def collect(root):
    rows = []
    for rel, full in in_scope(root):
        ftype, title, status = read_frontmatter(full)
        rows.append({
            "path": rel.replace(os.sep, "/"),
            "type": ftype or "unclassified",
            "title": title or os.path.basename(rel),
            "status": status or "",
        })
    rows.sort(key=lambda r: r["path"])
    return rows


def render(rows):
    out = [
        "# Documentation Index (DOCS.md)",
        "",
        "Generated by `scripts/docs_index.py`. Do not edit by hand.",
        "Governed by PLATFORM-STANDARDS section 14 and "
        "`docs/documentation-policy.md`.",
        "",
        f"Total in-scope documents: {len(rows)}",
        "",
    ]
    by_type = {}
    for r in rows:
        by_type.setdefault(r["type"], []).append(r)
    for t in TYPE_ORDER + sorted(k for k in by_type if k not in TYPE_ORDER):
        if t not in by_type:
            continue
        out.append(f"## {t} ({len(by_type[t])})")
        out.append("")
        for r in by_type[t]:
            status = f" [{r['status']}]" if r["status"] else ""
            out.append(f"- [`{r['path']}`]({r['path']}): {r['title']}{status}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def cmd_generate(root):
    content = render(collect(root))
    with open(os.path.join(root, INDEX_FILE), "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"wrote {INDEX_FILE} ({content.count(chr(10))} lines)")
    return 0


def cmd_check(root, strict):
    rows = collect(root)
    index_path = os.path.join(root, INDEX_FILE)
    findings = []
    try:
        with open(index_path, "r", encoding="utf-8") as fh:
            index_text = fh.read()
    except OSError:
        findings.append(f"{INDEX_FILE} is missing")
        index_text = ""
    for r in rows:
        if f"]({r['path']})" not in index_text:
            findings.append(f"not indexed: {r['path']}")
    for line in index_text.splitlines():
        if line.startswith("- [`"):
            try:
                p = line.split("](", 1)[1].split(")", 1)[0]
            except IndexError:
                continue
            if not os.path.exists(os.path.join(root, p)):
                findings.append(f"index entry does not resolve: {p}")
    if findings:
        print("Documentation index findings:")
        for f in findings:
            print(f"  - {f}")
        if strict:
            return 1
        print("(advisory; not failing the build)")
    else:
        print("documentation index OK")
    return 0


def main(argv):
    if len(argv) < 2 or argv[1] not in ("generate", "check"):
        print(__doc__)
        return 2
    args = argv[2:]
    strict = "--strict" in args
    args = [a for a in args if a != "--strict"]
    root = args[0] if args else "."
    root = os.path.abspath(root)
    if argv[1] == "generate":
        return cmd_generate(root)
    return cmd_check(root, strict)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
